version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  front:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always